version: 1
disable_existing_loggers: False
formatters:
    json:
        format: '{"@timestamp":"%(asctime)s", "level":"%(levelname)s", "module_name":"%(name)s","msg":%(message)s}'
    simple:
        format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: json
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: json
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: False

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
